## Importing the libraries

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [33]:
dataset = pd.read_csv('/content/Thyroid_Diff.csv')
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Age                   383 non-null    int64 
 1   Gender                383 non-null    object
 2   Smoking               383 non-null    object
 3   Hx Smoking            383 non-null    object
 4   Hx Radiothreapy       383 non-null    object
 5   Thyroid Function      383 non-null    object
 6   Physical Examination  383 non-null    object
 7   Adenopathy            383 non-null    object
 8   Pathology             383 non-null    object
 9   Focality              383 non-null    object
 10  Risk                  383 non-null    object
 11  T                     383 non-null    object
 12  N                     383 non-null    object
 13  M                     383 non-null    object
 14  Stage                 383 non-null    object
 15  Response              383 non-null    ob

In [34]:
from sklearn.preprocessing import LabelEncoder
dataset['Gender'] = le.fit_transform(dataset['Gender'])
dataset['Smoking'] = le.fit_transform(dataset['Smoking'])
dataset['Hx Smoking'] = le.fit_transform(dataset['Hx Smoking'])
dataset['Hx Radiothreapy'] = le.fit_transform(dataset['Hx Radiothreapy'])
dataset['Thyroid Function'] = le.fit_transform(dataset['Thyroid Function'])
dataset['Physical Examination'] = le.fit_transform(dataset['Physical Examination'])
dataset['Adenopathy'] = le.fit_transform(dataset['Adenopathy'])
dataset['Pathology'] = le.fit_transform(dataset['Pathology'])
dataset['Focality'] = le.fit_transform(dataset['Focality'])
dataset['Risk'] = le.fit_transform(dataset['Risk'])
dataset['T'] = le.fit_transform(dataset['T'])
dataset['N'] = le.fit_transform(dataset['N'])
dataset['M'] = le.fit_transform(dataset['M'])
dataset['Stage'] = le.fit_transform(dataset['Stage'])
dataset['Response'] = le.fit_transform(dataset['Response'])
dataset['Recurred'] = le.fit_transform(dataset['Recurred'])

## Importing the dataset

In [35]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values



## Splitting the dataset into the Training set and Test set

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Logistic Regression model on the Training set

In [38]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Making the Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[63  3]
 [ 6 24]]


0.90625

# Decision Tree Classification

In [40]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Making the Confusion Matrix

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[63  3]
 [ 4 26]]


0.9270833333333334

## Training the Random Forest Classification model on the Training set

In [42]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Making the Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[65  1]
 [ 4 26]]


0.9479166666666666

## Training the K-NN model on the Training set

In [44]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Making the Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[66  0]
 [10 20]]


0.8958333333333334

## Training the SVM model on the Training set

In [46]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Making the Confusion Matrix

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[62  4]
 [ 4 26]]


0.9166666666666666